---
# tasks file for /home/student/mycode/roles/dell.poweredge
 - name: Power on the PowerEdge
    redfish_powerstate:
    #  dellemc/openmanage/redfish_powerstate.py --idrac_ip 10.0.0.89 --idrac_user root --idrac_password r0gerwilc0 --validate_certs False
       baseuri: "{{ idrac_ip }}"
       username: "{{ idrac_user }}"
       password:  "{{ idrac_password }}"
       var: results
