---
# tasks file for /home/student/mycode/roles/dell.poweredge
# NOT WORKING!!!
- name: Power on the PowerEdge
  #  dellemc/openmanage/redfish_powerstate.py --idrac_ip 10.0.0.89 --idrac_user root --idrac_password r0gerwilc0 --validate_certs False
  # important to place this in quotes - PyYAML 1.1 reads Yes/No/On/Off as BOOLEAN
    reset_type: "On"   # turns on the device 
    register: results  # create a variable called "results"

  # print to screen
- name: Display facts gathered about the powerstate
    debug:
      var: results
